version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
   # image: backend22 #first we need to create image by docker build 
    build : . # if we do not have image then it will create then run 
    container_name: backend_app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://mongodb123:27017"

volumes:
  mongodb_data:
